# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HenriPotier' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  pod 'AFNetworking', '~> 3.0'
  
  # use_frameworks!

  # Pods for HenriPotier

  target 'HenriPotierTests' do
    inherit! :search_paths
    # Pods for testing
    pod "Specta"
    pod "Expecta"
    pod "KPAViewControllerTestHelper"
  end

  target 'HenriPotierUITests' do
    inherit! :search_paths
    pod "Specta"
    pod "Expecta"
    pod "KPAViewControllerTestHelper"
  end

end